### ISSUE TITLE
ikeeperConfiguration.properties - testVersion property is not working

### ISSUE THREAD

**Issue by bouskaJ** [ibek/issue-keeper#13]
testVersion is read from the config file and then is correctly set in [static section](https://github.com/ibek/issue-keeper/blob/78b50ca6bf022dc7468a3b71718c36e881dccfc2/issue-keeper-base/src/main/java/qa/tools/ikeeper/test/IKeeperConnector.java#L112)

But during the initialization is this property rewritten to null (when I does not set testVersion in constructor).

I think [here](https://github.com/ibek/issue-keeper/blob/78b50ca6bf022dc7468a3b71718c36e881dccfc2/issue-keeper-base/src/main/java/qa/tools/ikeeper/test/IKeeperConnector.java#L52) should be something like
`if(testVersion != null){
    IKeeperConnector.testVersion = testVersion;
}`

**Comment by ibek** [comment]
Thank you @bouskaJ for reporting and investigating the issue - you are right, there should be the condition.

**Comment by bouskaJ** [comment]
This fix breaks some unit tests. Fixed in [https://github.com/ibek/issue-keeper/pull/15](https://github.com/ibek/issue-keeper/pull/15).
