### ISSUE TITLE
Resource [logback.xml] occurs multiple times on the classpath

### ISSUE THREAD

**Issue by bouskaJ** [ibek/issue-keeper#18]
SUREFIRE-859: 12:34:28,349 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
SUREFIRE-859: 12:34:28,349 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/jbouska/.m2/repository/link/bek/tools/issue-keeper-base/2.5.0/issue-keeper-base-2.5.0.jar!/logback.xml]

I checked a few resources online and it seems like logback config files should be excluded from published jars:
https://stackoverflow.com/questions/18263139/how-do-i-suppress-a-inherited-projects-logback-xml-file-2-logback-xml-in-a-sing/18275945#18275945

https://www.mkyong.com/maven/maven-exclude-logback-xml-in-jar-file/

**Comment by bouskaJ** [comment]
https://github.com/ibek/issue-keeper/pull/19

**Comment by ibek** [comment]
#19 merged
