### ISSUE TITLE
Support regular expressions in constraints

### ISSUE THREAD

**Issue by livthomas** [ibek/issue-keeper#4]
It is not possible to add something like this to ikeeperConstraints.properties:

1271247-db=sybase*

It would be nice to be able to use regular expressions in these constraints.

**Comment by livthomas** [comment]
I have just realized that this is more important that I thought. Sometimes you have constraints like this:

@IssueConstraints({
        @IssueConstraint(id = "1180509", variable = "db", value = "oracle12c"),
        @IssueConstraint(id = "1180509", variable = "db", value = "oracle11gR2")
    })

So you would need to put this to ikeeperConstraints.properties:

1180509-db=oracle12c
1180509-db=oracle11gR2

But you cannot put two same keys into properties file. Regular expressions seem like the best solution of this problem:

1180509-db=oracle*

**Comment by ibek** [comment]
Tom, that's brilliant idea, regular expressions. Meanwhile, you can separate the database with comma:

1180509-db=oracle12c,oracle11gR2
https://github.com/ibek/issue-keeper/blob/master/issue-keeper-junit/src/test/resources/ikeeperConstraints.properties#L12

**Comment by ibek** [comment]
@livthomas  now it should be possible as follows (notice the tilde before the equality sign):

JBPM-3067-db~=Oracle.*
