### ISSUE TITLE
Do not run @BeforeClass method when there is @BZ annotation on class

### ISSUE THREAD

**Issue by livthomas** [ibek/issue-keeper#5]
I have noticed that when you have @BZ annotation on your class and you have a code afftected by that BZ in @BeforeClass method, it will be executed and there will be one test fail in the Surefire report. Can you somehow skip execution of @BeforeClass method when there is @BZ annotation on a class and the referenced BZ is still open?

**Comment by ibek** [comment]
@livthomas  - look at this test to see how it can be accomplished in junit 4.12 https://github.com/ibek/issue-keeper/blob/master/issue-keeper-junit/src/test/java/qa/tools/ikeeper/test/BZBeforeClassTest.java ... let me know whether it works for you
