### ISSUE TITLE
Allow to easily disable Issue Keeper for a single test suite run

### ISSUE THREAD

**Issue by livthomas** [ibek/issue-keeper#6]
Sometimes I want to run a test which has the associated BZ or JIRA still open. At the moment there is no other way how to do it except of removing the annotation from the source code. However, it is not the best solution to always make these small changes in a repository just because of a single test suite run.

Consider adding a system property which will disable Issue Keeper and run all the tests which would otherwise be ignored. Also consider adding a system property which will allow you to specify some BZs or JIRAs and then run the tests associated with them regardless of issue states.

**Comment by ibek** [comment]
@livthomas I added a new system property (-Dikeeper.run=false) which disables Issue Keeper. Another option is to set it in the ikeeperConfiguration.properties
